name: CI

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t arabic-words-bot:latest .

      - name: Save Docker image as tar file
        run: docker save -o arabic-words-bot.tar arabic-words-bot:latest

      - name: Transfer Docker image to remote server
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.PRIVATE_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          scp -o StrictHostKeyChecking=no arabic-words-bot.tar ${{ secrets.REMOTE_SERVER_USERNAME }}@${{ secrets.REMOTE_SERVER_ADDRESS }}:${{ secrets.REMOTE_SERVER_PATH }}

      - name: Load Docker image on remote server
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.REMOTE_SERVER_USERNAME }}@${{ secrets.REMOTE_SERVER_ADDRESS }} << 'ENDSSH'
          docker load -i ${{ secrets.REMOTE_SERVER_PATH }}/arabic-words-bot.tar
          rm -rf ${{ secrets.REMOTE_SERVER_PATH }}/arabic-words-bot.tar
          ENDSSH

      - name: Deploy Docker containers on remote server
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.REMOTE_SERVER_USERNAME }}@${{ secrets.REMOTE_SERVER_ADDRESS }} << 'ENDSSH'
          docker stop arabic-words-bot
          docker rm arabic-words-bot
          docker run --name arabic-words-bot -e ARABIC_WORDS_TELEGRAM_BOT_TOKEN=${{ secrets.ARABIC_WORDS_TELEGRAM_BOT_TOKEN }} -e MONGODB_URI=${{ secrets.MONGODB_URI }} --detach arabic-words-bot:latest
          ENDSSH
